### ISSUE TITLE
AzureWebJobsTraceWriter sink does not log Debug and Verbose level messages 

### ISSUE THREAD

**Issue by jeroenwo** [StarRez/Serilog.Sinks.AzureWebJobsTraceWriter#7]
I have setup an Azure function using the AzureWebJobsTraceWriter sink with the following code using NuGet package v1.0.22:
```csharp
var logger = new LoggerConfiguration().MinimumLevel.Verbose().WriteTo.TraceWriter(log).WriteTo.Trace().CreateLogger();

logger.Verbose("Verbose");
logger.Debug("Debug");
logger.Information("Info");
logger.Warning("Warning");
```

The Trace sink logs all level messages:
```
2017-12-12 13:42:48.354 +01:00 [Verbose] Verbose
2017-12-12 13:42:48.367 +01:00 [Debug] Debug
func.exe Information: 0 : 2017-12-12 13:42:48.368 +01:00 [Information] Info
func.exe Warning: 0 : 2017-12-12 13:42:48.372 +01:00 [Warning] Warning
```

The AzureWebJobsTraceWriter only logs the Information level and higher messages:
```
[12/12/2017 12:42:48 PM] 2017-12-12 13:42:48.368 +01:00 [Information] Info
[12/12/2017 12:42:48 PM] 2017-12-12 13:42:48.372 +01:00 [Warning] Warning
```

I am not aware that I need to configure something else?

**Comment by jeroenwo** [comment]
PS: the logging works in the Azure Function environment, but not in the local emulator. Any idea why?

**Comment by vludax** [comment]
To see Debug level logs in the emulator, please set "consoleLevel" to "verbose" in host.json.
https://docs.microsoft.com/en-au/azure/azure-functions/functions-host-json has more info.

**Comment by jeroenwo** [comment]
Wonderful, thanks, that works!
